Feature/Ayan's refinement
nevilparmar11/SDP_Online_Assessment_System pull request #19
Opened 2021-02-23 17:32 UTC by ayanshaikh18

Features Added :-

* Submission Reevaluation after Add/Delete of test cases.
* Run code by taking custom input from user.
* Take code as file input from user.

2021-02-23 18:56 UTC, jwalit21 requested changes
Just remove API keys as those are public.

2021-02-23 19:41 UTC, nevilparmar11 commented
> Just remove API keys as those are public.

Use env variable instead.

2021-02-24 04:15 UTC, ayanshaikh18 commented
Okay. I have remove public access of our API keys.

2021-02-24 04:18 UTC, jwalit21 approved these changes

2021-02-24 05:13 UTC, nevilparmar11 approved these changes

2021-02-24 05:14 UTC, merged